### ISSUE TITLE
BulletKinesis breaks on Update 105 Experimental 1

### ISSUE THREAD

**Issue by mrwallace888** [Osa-H3VR/BulletGrabber#1]
It's a given that mods are going to break on the Experimental branch, that's why it's an Experimental branch of course. Unfortunately, BulletKinesis suffers this fate.

**Comment by OsaPL** [comment]
Just closing this issue with the comment: I only support main branch with my mods.
If you want to use them on Experimental/Beta branches, things can be broken.
